### ISSUE TITLE
Ensure that packet headers are written in LE

### ISSUE THREAD

**Issue by kasperisager** [mafintosh/libudx#28]
https://github.com/mafintosh/libudx/blob/615860d0c0cf1f6102d07b36364ac1f91434d9b7/src/udx.c#L91-L100

**Comment by kasperisager** [comment]
@mafintosh If we go with network byte order, we can use the standard socket conversion functions: https://man7.org/linux/man-pages/man3/byteorder.3.html

**Comment by mafintosh** [comment]
Ah yes, but we should go LE always. We do that across stack so making it BE one place doesn't really help and 99% of systems are LE anyway

**Comment by kasperisager** [comment]
Makes perfect sense 👍
